// packages/example-react/src/App.tsx
import React, { useState } from 'react'
import './App.css'
import { useDi } from './use-di'
import { FooCmd } from './foo-cmd'
import { BarQry } from './bar-qry'
import { QuxCmd } from './qux-cmd'
import { BazQry } from './baz-qry'

function App() {
  const [result, setResult] = useState(0)
  const fooCmd = useDi(FooCmd)
  const barQry = useDi(BarQry)
  const quxCmd = useDi(QuxCmd)
  const bazQry = useDi(BazQry)
  return (
    <div className="App">
      <button onClick={() => fooCmd.execute(1)}>Invalidate Bar</button>
      <button onClick={() => quxCmd.execute(1)}>Invalidate Baz</button>
      <button onClick={() => barQry.execute().then(setResult)}>Bar</button>
      <button onClick={() => bazQry.execute().then(setResult)}>Baz</button>

      <h2>Result</h2>
      <p>{result}</p>
    </div>
  )
}

export default App

// examples/example-angular/src/app/app.component.ts
import { Component } from '@angular/core'
import { BarQry } from './bar-qry'
import { FooCmd } from './foo-cmd'
import { BazQry } from './baz-qry'
import { QuxCmd } from './qux-cmd'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  result?: number

  constructor(
    private readonly fooCmd: FooCmd,
    private readonly barQry: BarQry,
    private readonly bazQry: BazQry,
    private readonly quxCmd: QuxCmd
  ) {}

  foo() {
    this.fooCmd.execute(1)
  }

  async bar() {
    this.result = await this.barQry.execute()
  }

  async baz() {
    this.result = await this.bazQry.execute()
  }

  qux() {
    this.quxCmd.execute(1)
  }
}

<button (click)="foo()">Invalidate Bar</button>
<button (click)="qux()">Invalidate Baz</button>
<button (click)="bar()">Bar</button>
<button (click)="baz()">Baz</button>

<h2>Result</h2>
<p>{{ result }}</p>
<h2>Bar called</h2>
<span>{{ calls }}</span>
